apiVersion: v1
kind: PersistentVolume
metadata:
  name: kanban-data-pv
  namespace: kanban-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/postgresql/data
  persistentVolumeReclaimPolicy: Retain
