apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kanban-data-pvc
  namespace: kanban-namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  
