apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-app
  template:
    metadata:
      labels:
        app: kanban-app
    spec:
      containers:
        - name: kanban-app
          image: {{ .Values.kanbanApp.image }}
          ports:
            - containerPort: 8080
          env:
            - name: DB_SERVER
              value: kanban-postgres
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.username }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.password }}
