apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-ui-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-ui
  template:
    metadata:
      labels:
        app: kanban-ui
    spec:
      containers:
        - name: kanban-ui
          image: {{ .Values.kanbanUI.image }}
          ports:
            - containerPort: 80
