apiVersion: v1
kind: PersistentVolume
metadata:
  name: kanban-data-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.path }}
  persistentVolumeReclaimPolicy: Retain
